# Generated by Django 5.0.7 on 2024-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageoption_duration_time'),
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unavailabletimeslot',
            unique_together={('package', 'start_time', 'end_time')},
        ),
        migrations.AlterField(
            model_name='unavailabletimeslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unavailabletimeslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='unavailabletimeslot',
            name='date',
        ),
    ]
