# Generated by Django 5.0.7 on 2024-08-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageoption_duration_time'),
        ('timeslots', '0002_alter_unavailabletimeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabletimeslot',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='unavailabletimeslot',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.AlterUniqueTogether(
            name='unavailabletimeslot',
            unique_together={('package', 'start_datetime', 'end_datetime')},
        ),
    ]
