# Generated by Django 5.0.7 on 2024-08-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '리뷰 (촬영 패키지 후기)', 'verbose_name_plural': '리뷰 (촬영 패키지 후기)'},
        ),
    ]
