# Generated by Django 5.0.7 on 2024-08-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': '채팅방', 'verbose_name_plural': '채팅방'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '메시지', 'verbose_name_plural': '메시지'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
