# Generated by Django 5.0.7 on 2024-08-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chatroom',
            new_name='room',
        ),
    ]
