# Generated by Django 5.0.7 on 2024-09-09 05:24

import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '패키지 정책',
                'verbose_name_plural': '패키지 정책',
            },
        ),
        migrations.CreateModel(
            name='PackageProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_email', models.EmailField(max_length=254)),
                ('inquiry_phone_number', models.CharField(max_length=20)),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kakao_channel_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '패키지 제공자 정보',
                'verbose_name_plural': '패키지 제공자 정보',
            },
        ),
        migrations.CreateModel(
            name='PackageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': '패키지 검색용 태그',
                'verbose_name_plural': '패키지 검색용 태그',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('시즌패키지', '시즌패키지'), ('야외스냅', '야외스냅'), ('웨딩', '웨딩'), ('프로필', '프로필'), ('바디프로필', '바디프로필'), ('반려동물', '반려동물'), ('기본촬영대행', '기본촬영대행')], default='프로필', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('thumbnail_store_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('summary', models.TextField()),
                ('html_content', models.TextField()),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=3)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagepolicy')),
                ('provider_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packageprovider')),
            ],
            options={
                'verbose_name': '패키지',
                'verbose_name_plural': '패키지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_time', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('additional_person_price', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'verbose_name': '패키지 옵션',
                'verbose_name_plural': '패키지 옵션',
            },
        ),
        migrations.CreateModel(
            name='PackagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.ImageField(upload_to='')),
                ('store_url', models.ImageField(upload_to='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'verbose_name': '패키지 소개 이미지',
                'verbose_name_plural': '패키지 소개 이미지',
            },
        ),
        migrations.CreateModel(
            name='PackageTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='packages.packagetag')),
            ],
            options={
                'verbose_name': '패키지 + 태그',
                'verbose_name_plural': '패키지 + 태그',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='packages.PackageTaggedItem', to='packages.PackageTag', verbose_name='Tags'),
        ),
    ]
