# Generated by Django 5.0.7 on 2024-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagepicture',
            old_name='image',
            new_name='original_url',
        ),
        migrations.AddField(
            model_name='packagepicture',
            name='store_url',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
