# Generated by Django 5.0.7 on 2024-08-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageoption',
            old_name='delivery_fee',
            new_name='additional_person_price',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='is_delivered',
        ),
    ]
