# Generated by Django 5.0.7 on 2024-08-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageReview',
        ),
    ]
