# Generated by Django 5.0.7 on 2024-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_image_packagepicture_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='packagepicture',
            name='original_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='packagepicture',
            name='store_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
