# Generated by Django 5.0.7 on 2024-08-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_delivery_fee_packageoption_additional_person_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoption',
            name='duration_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
