# Generated by Django 5.0.7 on 2024-09-05 05:28

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_id_alter_packagetaggeditem_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagetaggeditem',
            name='object_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22),
        ),
    ]
