# Generated by Django 5.0.7 on 2024-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='thumbnail_store_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
