# Generated by Django 5.0.7 on 2024-09-02 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_thumbnail_store_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': '패키지', 'verbose_name_plural': '패키지'},
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.CharField(editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagetaggeditem',
            name='object_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=22),
        ),
    ]
