# Generated by Django 5.0.7 on 2024-09-02 11:27

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_options_alter_package_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagetaggeditem',
            name='object_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22),
        ),
    ]
