# Generated by Django 5.0.7 on 2024-09-12 06:15

import api.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=api.accounts.models.save_user_avatar),
        ),
    ]
