# Generated by Django 5.0.7 on 2024-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='익명의 사용자', max_length=100),
        ),
    ]
