# Generated by Django 5.0.7 on 2024-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/149/149071.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='안녕하세요, 저의 프로필에 방문해주셔서 감사합니다.'),
        ),
    ]
