# Generated by Django 5.0.7 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='manager_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='artist_name',
            new_name='real_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='user',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
