# Generated by Django 5.0.7 on 2024-08-14 01:42

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=128, prefix='', primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('에스크로 홀드', '에스크로 홀드'), ('에스크로 릴리스', '에스크로 릴리스'), ('에스크로 환불', '에스크로 환불'), ('결제완료', '결제완료'), ('결제취소', '결제취소')], default='대기중', max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
