# Generated by Django 5.0.7 on 2024-08-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='method',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('대기중', '대기중'), ('에스크로 홀드', '에스크로 홀드'), ('에스크로 릴리스', '에스크로 릴리스'), ('에스크로 환불', '에스크로 환불'), ('결제완료', '결제완료'), ('결제취소', '결제취소')], default='대기중', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
