# Generated by Django 5.0.7 on 2024-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_amount_remove_reservation_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationoption',
            old_name='delivery_fee',
            new_name='additional_person_price',
        ),
        migrations.RemoveField(
            model_name='reservationoption',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_people',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
