# Generated by Django 5.0.7 on 2024-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
