# Generated by Django 5.0.7 on 2024-08-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_delivery_fee_reservationoption_additional_person_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': '예약', 'verbose_name_plural': '예약'},
        ),
        migrations.AlterModelOptions(
            name='reservationoption',
            options={'ordering': ['-created_at'], 'verbose_name': '예약 당시 옵션', 'verbose_name_plural': '예약 당시 옵션'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional_people',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
