# Generated by Django 5.0.7 on 2024-09-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'verbose_name': '인터랙션', 'verbose_name_plural': '인터랙션'},
        ),
    ]
